config/routes.rb
Rails.application.routes.draw do
  resources :connections

  get '/', to: 'connections#index'
  get '/log', to: 'connections#new'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/connection.rb
class Connection < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  before_action :set_connection, only: [:show, :edit, :update, :destroy]

  # GET /connections
  # GET /connections.json
  def index
    @connections = Connection.all
  end

  # GET /connections/1
  # GET /connections/1.json
  def show
  end

  # GET /connections/new
  def new
    @connection = Connection.new
  end

  # GET /connections/1/edit
  def edit
  end

  # POST /connections
  # POST /connections.json
  def create
    @connection = Connection.new(connection_params)

    respond_to do |format|
      if @connection.save
        format.html { redirect_to @connection, notice: 'Connection was successfully created.' }
        format.json { render :show, status: :created, location: @connection }
      else
        format.html { render :new }
        format.json { render json: @connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /connections/1
  # PATCH/PUT /connections/1.json
  def update
    respond_to do |format|
      if @connection.update(connection_params)
        format.html { redirect_to @connection, notice: 'Connection was successfully updated.' }
        format.json { render :show, status: :ok, location: @connection }
      else
        format.html { render :edit }
        format.json { render json: @connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /connections/1
  # DELETE /connections/1.json
  def destroy
    @connection.destroy
    respond_to do |format|
      format.html { redirect_to connections_url, notice: 'Connection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_connection
      @connection = Connection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def connection_params
      params.require(:connection).permit(:ip, :zip)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/views/connections/_form.html.erb
<%= form_with(model: connection, local: true) do |form| %>
  <% if connection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(connection.errors.count, "error") %> prohibited this connection from being saved:</h2>

      <ul>
        <% connection.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :ip, value: request.remote_ip() %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/connections/edit.html.erb
<h1>Editing Connection</h1>

<%= render 'form', connection: @connection %>

<%= link_to 'Show', @connection %> |
<%= link_to 'Back', connections_path %>

app/views/connections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Connections</h1>

<table>
  <thead>
    <tr>
      <th>Ip</th>
      <th>Zip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @connections.each do |connection| %>
      <tr>
        <td><%= connection.ip %></td>
        <td><%= connection.zip %></td>
        <td><%= link_to 'Show', connection %></td>
        <td><%= link_to 'Edit', edit_connection_path(connection) %></td>
        <td><%= link_to 'Destroy', connection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Connection', new_connection_path %>

app/views/connections/new.html.erb
<h1>New Connection</h1>

<%= render 'form', connection: @connection %>

<%= link_to 'Back', connections_path %>

app/views/connections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ip:</strong>
  <%= @connection.ip %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @connection.zip %>
</p>

<%= link_to 'Edit', edit_connection_path(@connection) %> |
<%= link_to 'Back', connections_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Connections</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>